# Generated by Django 6.0.4 on 2026-05-27 04:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_transaccion', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, verbose_name='ID de Transacción')),
                ('cuenta', models.CharField(choices=[('wallet_usuario', 'Billetera del Usuario'), ('casa', 'Casa de Apuestas'), ('apuestas_pendientes', 'Apuestas Pendientes'), ('bonos', 'Bonos')], max_length=30, verbose_name='Cuenta')),
                ('monto', models.DecimalField(decimal_places=4, max_digits=18, verbose_name='Monto')),
                ('direccion', models.CharField(choices=[('DEBIT', 'Débito'), ('CREDIT', 'Crédito')], max_length=6, verbose_name='Dirección')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asientos_contables', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Asiento Contable',
                'verbose_name_plural': 'Asientos Contables',
                'ordering': ['-creado'],
            },
        ),
    ]
